name: fctracker

services:
  app:
    dns:
    - 8.8.8.8
    - 8.8.4.4
    container_name: fctracker-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: ${PORT}
      GIN_MODE: ${GIN_MODE}
      MONGODB_URI: "${MONGODB_URI}"
    env_file:
      - .env
    expose:
      - "9090"
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - fctracker-backend
      - proxy_network

networks:
  fctracker-backend:
    driver: bridge
    enable_ipv6: false
  proxy_network:
    external: true
